databases:
  - name: sisepeu_whfo
    databaseName: sisepeu_whfo
    user: sisepeu_whfo_user

services:
  - type: web
    name: sisepeu_whfo
    env: python
    buildCommand: "./render/build.sh"
    startCommand: "gunicorn sisepeu.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sisepeu
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
