# Generated by Django 3.2.19 on 2023-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='ANIO')),
                ('universidad', models.CharField(max_length=200, verbose_name='UNIVERSIDAD')),
                ('facultad', models.CharField(max_length=200, verbose_name='FACULTAD')),
                ('carrera', models.CharField(max_length=200, verbose_name='CARRERA')),
                ('cantidad', models.IntegerField(verbose_name='CANTIDAD')),
            ],
        ),
    ]
